### PR TITLE
Require space between `async` and arrow function

### PR DESCRIPTION
**Pull request by tassoevan**

### CODE REVIEW

**Comment by sampaiodiego** [comment]
nice! I have many others items I'd like to change, let me give a look at them to see if this is not accomplished by them.

**Comment by sampaiodiego** [comment]
this closes https://github.com/RocketChat/eslint-config-rocketchat/issues/1 as well

**Review by sampaiodiego — CHANGES_REQUESTED** [review]
the PR title says it's changing the `async` style, but it is changed for _anonymous_ as well..

we usually do:
`function() { ... }`

this will require us to change to:
`function () { ... }`

is that an intentional change?

**Comment by tassoevan** [comment]
Not really, but it's a style I prefer -- therefore I accidentally included it.

**Review by sampaiodiego — APPROVED** [review]

**Pull request merged**
